[package]
name = "kvs"
version = "0.1.0"
authors = ["Zhixiang Hao <haozx@buaa.edu.cn>"]
description = "A key-value store"
edition = "2018"

[dependencies]

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
